server:
  port: 8085
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/usermgmntdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: rkpal12cs39@gmail.com
    password: yrsqnvprkpeweunp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      
   
